version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.0

workflows:
  create-then-delete:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: eks-orb-demo
          aws-region: $AWS_DEFAULT_REGION
      - aws-eks/delete-cluster:
          cluster-name: eks-orb-demo
          aws-region: $AWS_DEFAULT_REGION
          wait: true
          requires:
            - aws-eks/create-cluster
